name: Validate commit

on:
  push:
    branches: [actions]
  pull_request:
    branches: [actions]

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          channels: anaconda, conda-forge
          auto-update-conda: true
          auto-activate-base: false
          environment-file: conda_history.yml
          activate-environment: oratio
      - run: conda --version
      - name: Lint with flake8
        run: |
          conda install flake8
          conda list
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
